import { notFound } from "next/navigation";
import { ProjectForm } from "@/components/admin/project-form";
import { ImageUpload } from "@/components/admin/image-upload";
import { ConfirmSubmitButton } from "@/components/admin/confirm-submit-button";
import { UnitManager } from "@/components/admin/unit-manager";
import { FloorPlanManager } from "@/components/admin/floor-plan-manager";
import { getProjects } from "@/repositories/projects";
import { addImageAction, deleteImageAction, deleteProjectAction } from "@/app/admin/actions";
import { DeleteProjectButton } from "@/components/admin/delete-project-button";
export default async function EditProject({params}:{params:Promise<{id:string}>}){const {id}=await params;const project=(await getProjects()).find(p=>p.id===Number(id));if(!project)notFound();return <><p className="eyebrow mb-4">Projekti</p><h1 className="text-5xl tracking-[-.05em]">{project.title}</h1><ProjectForm project={project}/><nav className="mt-10 flex max-w-5xl flex-wrap items-center gap-2 border border-black/10 bg-white p-4 text-sm"><span className="mr-2 font-medium text-black/55">Popunite ostale podatke:</span><a href="#galerija" className="bg-black/5 px-4 py-1.5 hover:bg-black/10">1 · Galerija / renderi</a><a href="#stanovi" className="bg-black/5 px-4 py-1.5 hover:bg-black/10">2 · Stanovi / lokali</a><a href="#osnove" className="bg-black/5 px-4 py-1.5 hover:bg-black/10">3 · Osnove (2D / 3D)</a></nav><section id="galerija" className="mt-14 max-w-5xl scroll-mt-24 border-t border-black/15 pt-10"><h2 className="text-3xl">Galerija / renderi</h2><div className="mt-6 grid gap-2">{project.images.map(image=><div key={image.id} className="flex justify-between bg-white p-4"><span>{image.altText} · {image.type}</span><form action={deleteImageAction}><input type="hidden" name="id" value={image.id}/><input type="hidden" name="projectId" value={project.id}/><ConfirmSubmitButton message={`Obrisati sliku „${image.altText||image.type}“?`} confirmLabel="Obriši sliku" className="text-red-700">Obriši</ConfirmSubmitButton></form></div>)}</div><form action={addImageAction} className="mt-6 grid gap-4 bg-white p-6 md:grid-cols-2"><input type="hidden" name="projectId" value={project.id}/><div className="md:col-span-2"><ImageUpload name="imagePath" label="Nova slika"/></div><div className="form-field"><label>Alt tekst</label><input name="altText"/></div><div className="form-field"><label>Tip</label><select name="type"><option>GALLERY</option><option>RENDER</option><option>EXTERIOR</option><option>INTERIOR</option><option>FLOOR_PLAN</option></select></div><button className="button justify-self-start">Dodaj sliku</button></form></section><div id="stanovi" className="scroll-mt-24"><UnitManager project={project}/></div><div id="osnove" className="scroll-mt-24"><FloorPlanManager project={project}/></div><section className="mt-20 max-w-5xl border-t border-red-300 pt-8"><h2 className="text-2xl text-red-800">Opasna zona</h2><p className="mt-3 max-w-xl text-sm leading-relaxed text-red-900/70">Brisanjem projekta trajno se uklanjaju i sve njegove slike, osnove i stambene ili poslovne jedinice.</p><form action={deleteProjectAction} className="mt-5"><input type="hidden" name="id" value={project.id}/><DeleteProjectButton title={project.title} /></form></section></>}
