CREATE DATABASE IF NOT EXISTS storms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE storms;

CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category ENUM('APARTMENT','COMMERCIAL','LUXURY') NOT NULL,
  status ENUM('DRAFT','ACTIVE','COMPLETED') NOT NULL DEFAULT 'DRAFT',
  title VARCHAR(180) NOT NULL,
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  slug VARCHAR(190) NOT NULL UNIQUE,
  shortDescription TEXT NOT NULL,
  description LONGTEXT NOT NULL,
  address VARCHAR(255) NOT NULL,
  city VARCHAR(120) NOT NULL DEFAULT 'Beograd',
  locationDescription TEXT NOT NULL,
  heroImage VARCHAR(500) NOT NULL,
  mapAddress VARCHAR(255) NOT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  showInNavigation BOOLEAN NOT NULL DEFAULT TRUE,
  sortOrder INT NOT NULL DEFAULT 0,
  seoTitle VARCHAR(190) NULL,
  seoDescription VARCHAR(320) NULL,
  titleEn VARCHAR(180) NULL,
  subtitleEn VARCHAR(255) NULL,
  shortDescriptionEn TEXT NULL,
  descriptionEn LONGTEXT NULL,
  locationDescriptionEn TEXT NULL,
  seoTitleEn VARCHAR(190) NULL,
  seoDescriptionEn VARCHAR(320) NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_projects_public (status, category, showInNavigation, sortOrder),
  INDEX idx_projects_featured (status, featured, sortOrder)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS project_images (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  projectId BIGINT UNSIGNED NOT NULL,
  imagePath VARCHAR(500) NOT NULL,
  altText VARCHAR(255) NOT NULL DEFAULT '',
  type ENUM('GALLERY','RENDER','EXTERIOR','INTERIOR','FLOOR_PLAN','OTHER') NOT NULL DEFAULT 'GALLERY',
  sortOrder INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_project_images_project FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE,
  INDEX idx_project_images_order (projectId, sortOrder)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS units (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  projectId BIGINT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  unitNumber VARCHAR(80) NOT NULL DEFAULT '',
  floor VARCHAR(80) NOT NULL DEFAULT '',
  rooms DECIMAL(4,1) NULL,
  area DECIMAL(10,2) NOT NULL,
  orientation VARCHAR(160) NOT NULL DEFAULT '',
  price DECIMAL(14,2) NULL,
  showPrice BOOLEAN NOT NULL DEFAULT TRUE,
  status ENUM('AVAILABLE','RESERVED','SOLD') NOT NULL DEFAULT 'AVAILABLE',
  description TEXT NULL,
  image VARCHAR(500) NULL,
  floorPlanImage VARCHAR(500) NULL,
  sortOrder INT NOT NULL DEFAULT 0,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_units_project FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE,
  INDEX idx_units_project_status (projectId, status, sortOrder)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS project_floor_plans (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  projectId BIGINT UNSIGNED NOT NULL,
  title VARCHAR(180) NOT NULL,
  image VARCHAR(500) NOT NULL,
  description TEXT NULL,
  sortOrder INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_floor_plans_project FOREIGN KEY (projectId) REFERENCES projects(id) ON DELETE CASCADE,
  INDEX idx_floor_plans_order (projectId, sortOrder)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  role VARCHAR(160) NOT NULL,
  photo VARCHAR(500) NOT NULL,
  description TEXT NULL,
  sortOrder INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_team_active_order (active, sortOrder)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS site_settings (
  settingKey VARCHAR(100) PRIMARY KEY,
  settingValue TEXT NOT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ipHash CHAR(64) NOT NULL,
  attemptedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  success BOOLEAN NOT NULL DEFAULT FALSE,
  INDEX idx_login_attempts_ip_time (ipHash, attemptedAt)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS inquiries (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category ENUM('APARTMENT','COMMERCIAL','LUXURY') NOT NULL,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(80) NOT NULL DEFAULT '',
  message TEXT NOT NULL,
  locale ENUM('sr','en') NOT NULL DEFAULT 'sr',
  sourcePath VARCHAR(255) NOT NULL DEFAULT '/kontakt',
  status ENUM('NEW','READ','ARCHIVED') NOT NULL DEFAULT 'NEW',
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_inquiries_status_date (status, createdAt),
  INDEX idx_inquiries_category_date (category, createdAt)
) ENGINE=InnoDB;
