USE storms;

INSERT INTO projects (id, category, status, title, subtitle, slug, shortDescription, description, address, city, locationDescription, heroImage, mapAddress, latitude, longitude, featured, showInNavigation, sortOrder) VALUES
(1,'APARTMENT','ACTIVE','Dobračina 21','Savremeni ritam Dorćola','dobracina-21','Promišljeno stanovanje u istorijskom jezgru Beograda.','Dobračina 21 spaja mir intimnog doma sa energijom Dorćola.','Dobračina 21','Beograd','Na nekoliko koraka od Dunava i najživljih gradskih ulica.','/images/projects/dobracina-21/hero-v2.png','Dobračina 21, Beograd',44.8218000,20.4619000,1,1,1),
(2,'COMMERCIAL','ACTIVE','K District Office','Prostor za ideje','k-district-office','Fleksibilan poslovni prostor projektovan za novi način rada.','Otvorene osnove, vrhunska infrastruktura i reprezentativan karakter.','Dunavski kej 23','Beograd','Poslovna zona uz Dunav.','https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=2200&q=90','Dunavski kej 23, Beograd',44.8280000,20.4550000,1,1,2),
(3,'LUXURY','ACTIVE','Skyline Penthouse','Privatni horizont Beograda','skyline-penthouse','Jedinstvena rezidencija sa panoramskim pogledom.','Monumentalna, ali intimna rezidencija oblikovana prirodnim materijalima.','Savski trg','Beograd','Pogled na Savu i novu promenadu.','/images/lux/penthouse-blue-hour.webp','Savski trg, Beograd',44.8062000,20.4474000,1,1,3),
(4,'APARTMENT','COMPLETED','Vračar Gardens','Arhitektura mirne ulice','vracar-gardens','Završena urbana rezidencija sa privatnim vrtovima.','Kuća savremenog izraza u dijalogu sa kontekstom Vračara.','Vračar','Beograd','Rezidencijalno susedstvo u blizini Hrama Svetog Save.','https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=2200&q=90','Vračar, Beograd',44.7990000,20.4750000,0,0,4)
ON DUPLICATE KEY UPDATE title=VALUES(title),heroImage=VALUES(heroImage),mapAddress=VALUES(mapAddress),latitude=VALUES(latitude),longitude=VALUES(longitude);

INSERT INTO projects (id,category,status,title,subtitle,slug,shortDescription,description,address,city,locationDescription,heroImage,mapAddress,latitude,longitude,featured,showInNavigation,sortOrder,titleEn,subtitleEn,shortDescriptionEn,descriptionEn,locationDescriptionEn) VALUES
(5,'APARTMENT','ACTIVE','Vračar Park','Dom okrenut zelenilu','vracar-park','Savremena rezidencija sa privatnim vrtom u tihom delu Vračara.','Toplina prirodnih materijala, privatnost i obilje dnevnog svetla.','Nebojšina 18','Beograd','Mirna rezidencijalna ulica u blizini Hrama.','/images/projects/vracar-park/hero.webp','Nebojšina 18, Beograd',44.7948,20.4687,1,1,2,'Vračar Park','A home facing the garden','A contemporary residence with a private garden in a quiet part of Vračar.','Natural materials, privacy and abundant daylight.','A calm residential street moments from the Church of Saint Sava.'),
(6,'APARTMENT','ACTIVE','Riverside Residence','Svetlo iznad reke','riverside-residence','Prostrani gradski stanovi sa panoramskim pogledom na Savu.','Čiste linije, velike terase i enterijeri oblikovani dnevnim svetlom.','Bulevar Nikole Tesle 12','Beograd','Direktno uz kej i poslovnu zonu Novog Beograda.','/images/projects/riverside-residence/hero.webp','Bulevar Nikole Tesle 12, Beograd',44.8165,20.4321,1,1,3,'Riverside Residence','Light above the river','Expansive city homes with panoramic views across the Sava.','Clean lines, deep terraces and interiors shaped by daylight.','Directly on the riverfront and close to New Belgrade business district.'),
(7,'COMMERCIAL','ACTIVE','Gallery 27','Prostor kao izložba','gallery-27','Reprezentativan retail prostor u istorijskom centru.','Svetao, prilagodljiv prostor galerijskog karaktera.','Kneza Mihaila 27','Beograd','Najprometnija pešačka zona grada.','/images/projects/gallery-27/hero.webp','Kneza Mihaila 27, Beograd',44.8171,20.4562,0,1,5,'Gallery 27','Space as exhibition','A distinguished retail space in the historic centre.','A bright, adaptable gallery-like space.','On the city''s principal pedestrian street.'),
(8,'COMMERCIAL','ACTIVE','Atrium Works','Nova kultura rada','atrium-works','Fleksibilan poslovni kampus oko zelenog atrijuma.','Dvovisinski zajednički prostori i modularne kancelarije.','Omladinskih brigada 88','Beograd','Srce poslovne zone Novog Beograda.','/images/projects/atrium-works/hero.webp','Omladinskih brigada 88, Beograd',44.8093,20.4083,0,1,6,'Atrium Works','A new culture of work','A flexible business campus organised around a planted atrium.','Double-height shared spaces and modular offices.','At the heart of New Belgrade''s business district.'),
(9,'LUXURY','ACTIVE','Aurora Sky Villa','Rezidencija iznad grada','aurora-sky-villa','Duplex sky-villa sa dvovisinskim salonom.','Dramatičan kamen, tamno drvo i precizno svetlo iznad grada.','Bulevar Vudroa Vilsona 16','Beograd','Iznad Savske promenade.','/images/projects/aurora-sky-villa/hero-v2.png','Bulevar Vudroa Vilsona 16, Beograd',44.8045,20.4452,1,1,8,'Aurora Sky Villa','A residence above the city','A duplex sky villa with a double-height salon.','Dramatic stone, dark timber and precise light above the city.','Above the Sava promenade with complete privacy.'),
(10,'LUXURY','ACTIVE','Nocturne Private Spa','Privatni ritual grada','nocturne-private-spa','Penthouse sa privatnim wellness paviljonom.','Tamna, taktilna rezidencija sa privatnim bazenom i spa zonom.','Tolstojeva 24','Beograd','Diskretna adresa na Dedinju.','/images/projects/nocturne-private-spa/hero-v2.png','Tolstojeva 24, Beograd',44.7798,20.4526,0,1,9,'Nocturne Private Spa','A private urban ritual','A penthouse with a private wellness pavilion.','A dark tactile residence with a private pool and spa.','A discreet Dedinje address surrounded by gardens.')
ON DUPLICATE KEY UPDATE title=VALUES(title),heroImage=VALUES(heroImage),titleEn=VALUES(titleEn);

INSERT INTO projects (id,category,status,title,subtitle,slug,shortDescription,description,address,city,locationDescription,heroImage,mapAddress,latitude,longitude,featured,showInNavigation,sortOrder,titleEn,subtitleEn,shortDescriptionEn,descriptionEn,locationDescriptionEn) VALUES
(11,'APARTMENT','COMPLETED','Kalemegdan Courtyard','Dvorište u srcu grada','kalemegdan-courtyard','Urbana rezidencija organizovana oko mirnog privatnog vrta.','Savremeni stanovi i precizna kamena fasada oblikovani oko intimnog pejzaža.','Cara Uroša 18','Beograd','Donji Dorćol, između Kalemegdana i Dunava.','/images/completed/kalemegdan-courtyard.png','Cara Uroša 18, Beograd',44.8234,20.4553,0,0,11,'Kalemegdan Courtyard','A courtyard at the heart of the city','An urban residence organised around a quiet private garden.','Contemporary homes and a precise stone facade shaped around an intimate landscape.','Lower Dorćol, between Kalemegdan and the Danube.'),
(12,'COMMERCIAL','COMPLETED','Danube Gate','Nova gradska kapija','danube-gate','Poslovno-stambena zgrada sa aktivnim prizemljem uz Dunav.','Završen gradski blok sa dubokim lođama i fasadom od opeke.','Dunavski kej 9','Beograd','Na spoju Dorćola, marine i dunavskog šetališta.','/images/completed/danube-gate.png','Dunavski kej 9, Beograd',44.8287,20.4564,0,0,12,'Danube Gate','A new urban gateway','A mixed-use building with an active ground floor beside the Danube.','A completed city block with deep loggias and a crafted brick facade.','Where Dorćol, the marina and the Danube promenade meet.'),
(13,'LUXURY','COMPLETED','Senjak Terraces','Arhitektura u krošnjama','senjak-terraces','Butik rezidencije sa velikim ozelenjenim terasama.','Mirne rezidencije uklopljene u padinu, sa kamenom, drvetom i pejzažom.','Vase Pelagića 32','Beograd','Zelena padina Senjaka sa diskretnim pristupom gradu.','/images/completed/senjak-terraces.png','Vase Pelagića 32, Beograd',44.7875,20.4348,0,0,13,'Senjak Terraces','Architecture among the trees','Boutique residences with generous planted terraces.','Calm homes embedded into the slope, shaped by stone, timber and landscape.','A green Senjak hillside with discreet access to the city.')
ON DUPLICATE KEY UPDATE title=VALUES(title),heroImage=VALUES(heroImage),titleEn=VALUES(titleEn);

INSERT INTO units (projectId,name,unitNumber,floor,rooms,area,orientation,price,showPrice,status,sortOrder) VALUES
(1,'Stan A01','A01','2. sprat',3,78.50,'Istok / Zapad',320000,1,'AVAILABLE',1),
(1,'Stan A04','A04','4. sprat',4,112.00,'Jug / Istok',NULL,0,'AVAILABLE',2),
(2,'Lokal L02','L02','Prizemlje',NULL,146.00,'Ulična strana',NULL,0,'AVAILABLE',1);

INSERT INTO project_images (projectId,imagePath,altText,type,sortOrder)
SELECT p.id, CASE p.slug WHEN 'dobracina-21' THEN '/images/projects/dobracina-21/hero-v2.png' WHEN 'skyline-penthouse' THEN '/images/lux/penthouse-blue-hour.webp' WHEN 'aurora-sky-villa' THEN '/images/projects/aurora-sky-villa/hero-v2.png' WHEN 'nocturne-private-spa' THEN '/images/projects/nocturne-private-spa/hero-v2.png' ELSE CONCAT('/images/projects/',p.slug,'/hero.webp') END, CONCAT(p.title,' — enterijer'),'INTERIOR',1 FROM projects p WHERE p.id IN (1,2,3,5,6,7,8,9,10)
UNION ALL SELECT p.id, CASE p.slug WHEN 'skyline-penthouse' THEN '/images/lux/penthouse-dining.webp' WHEN 'aurora-sky-villa' THEN '/images/projects/aurora-sky-villa/gallery-v2.png' WHEN 'nocturne-private-spa' THEN '/images/projects/nocturne-private-spa/gallery-v2.png' END, CONCAT(p.title,' — galerija'),'INTERIOR',2 FROM projects p WHERE p.id IN (3,9,10)
UNION ALL SELECT p.id, CASE p.slug WHEN 'dobracina-21' THEN '/images/projects/dobracina-21/plan-2d-v2.png' WHEN 'skyline-penthouse' THEN '/images/lux/penthouse-plan-2d.webp' ELSE CONCAT('/images/projects/',p.slug,'/plan-2d.webp') END, CONCAT(p.title,' — 2D osnova'),'FLOOR_PLAN',3 FROM projects p WHERE p.id IN (1,2,3,5,6,7,8,9,10)
UNION ALL SELECT p.id, CASE p.slug WHEN 'dobracina-21' THEN '/images/projects/dobracina-21/plan-3d-v2.png' WHEN 'skyline-penthouse' THEN '/images/lux/penthouse-plan-3d.webp' WHEN 'aurora-sky-villa' THEN '/images/projects/aurora-sky-villa/plan-3d-v2.png' WHEN 'nocturne-private-spa' THEN '/images/projects/nocturne-private-spa/plan-3d-v2.png' WHEN 'atrium-works' THEN '/images/projects/atrium-works/plan-3d-v2.png' ELSE CONCAT('/images/projects/',p.slug,'/plan-3d.webp') END, CONCAT(p.title,' — 3D prikaz'),'FLOOR_PLAN',4 FROM projects p WHERE p.id IN (1,2,3,5,6,7,8,9,10);

INSERT INTO project_images (projectId,imagePath,altText,type,sortOrder)
SELECT p.id,p.heroImage,p.title,'EXTERIOR',1 FROM projects p WHERE p.id IN (11,12,13);

INSERT INTO project_floor_plans (projectId,title,image,sortOrder)
SELECT p.id,'Arhitektonska 2D osnova',CASE p.slug WHEN 'dobracina-21' THEN '/images/projects/dobracina-21/plan-2d-v2.png' WHEN 'skyline-penthouse' THEN '/images/lux/penthouse-plan-2d.webp' ELSE CONCAT('/images/projects/',p.slug,'/plan-2d.webp') END,1 FROM projects p WHERE p.id IN (1,2,3,5,6,7,8,9,10)
UNION ALL SELECT p.id,'3D prostorni prikaz',CASE p.slug WHEN 'dobracina-21' THEN '/images/projects/dobracina-21/plan-3d-v2.png' WHEN 'skyline-penthouse' THEN '/images/lux/penthouse-plan-3d.webp' WHEN 'aurora-sky-villa' THEN '/images/projects/aurora-sky-villa/plan-3d-v2.png' WHEN 'nocturne-private-spa' THEN '/images/projects/nocturne-private-spa/plan-3d-v2.png' WHEN 'atrium-works' THEN '/images/projects/atrium-works/plan-3d-v2.png' ELSE CONCAT('/images/projects/',p.slug,'/plan-3d.webp') END,2 FROM projects p WHERE p.id IN (1,2,3,5,6,7,8,9,10);

INSERT INTO team_members (name,role,photo,sortOrder,active) VALUES
('Aleksandar Stojanović','Osnivač i direktor','https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=1200&q=85',1,1),
('Milica Ristić','Direktorka razvoja','https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=85',2,1);

INSERT INTO site_settings (settingKey,settingValue) VALUES
('companyName','STORMS'),('phone','+381 11 455 20 20'),('email','office@storms.rs'),('address','Beograd, Srbija'),
('contactHeading','Razgovarajmo o prostoru koji ostaje.'),('contactText','Za informacije o projektima i saradnji, naš tim vam je na raspolaganju.'),
('aboutTitle','Gradimo vrednost koja traje'),('aboutSubtitle','Preciznost u svakom detalju'),
('aboutDescription','STORMS je investiciona i građevinska kompanija posvećena stvaranju savremenih prostora visokog kvaliteta.'),('aboutImage','/images/about/material-studio.png'),
('footerText','Arhitektura. Izgradnja. Vrednost.')
ON DUPLICATE KEY UPDATE settingValue=VALUES(settingValue);
