"use server";
import { redirect } from "next/navigation";
import { revalidatePath, revalidateTag } from "next/cache";
import { z } from "zod";
import { getPool } from "@/lib/db";
import { destroySession, isAuthenticated } from "@/lib/auth/session";

async function guard(){if(!(await isAuthenticated()))redirect("/admin/login");}
const projectSchema=z.object({
  category:z.enum(["APARTMENT","COMMERCIAL","LUXURY"]),status:z.enum(["DRAFT","ACTIVE","COMPLETED"]),title:z.string().min(2),subtitle:z.string(),slug:z.string().min(2).regex(/^[a-z0-9-]+$/),shortDescription:z.string(),description:z.string(),address:z.string(),city:z.string(),locationDescription:z.string(),heroImage:z.string(),mapAddress:z.string(),featured:z.boolean(),showInNavigation:z.boolean(),seoTitle:z.string(),seoDescription:z.string(),titleEn:z.string(),subtitleEn:z.string(),shortDescriptionEn:z.string(),descriptionEn:z.string(),locationDescriptionEn:z.string(),seoTitleEn:z.string(),seoDescriptionEn:z.string()
});
const val=(fd:FormData,key:string)=>String(fd.get(key)||"").trim();
const refreshProjects=()=>{revalidateTag("projects","max");revalidatePath("/","layout");};

export async function saveProjectAction(formData:FormData){await guard();const id=Number(fdNumber(formData,"id"));const data=projectSchema.parse({category:val(formData,"category"),status:val(formData,"status"),title:val(formData,"title"),subtitle:val(formData,"subtitle"),slug:val(formData,"slug"),shortDescription:val(formData,"shortDescription"),description:val(formData,"description"),address:val(formData,"address"),city:val(formData,"city"),locationDescription:val(formData,"locationDescription"),heroImage:val(formData,"heroImage"),mapAddress:val(formData,"mapAddress"),featured:formData.get("featured")==="on",showInNavigation:formData.get("showInNavigation")==="on",seoTitle:val(formData,"seoTitle"),seoDescription:val(formData,"seoDescription"),titleEn:val(formData,"titleEn"),subtitleEn:val(formData,"subtitleEn"),shortDescriptionEn:val(formData,"shortDescriptionEn"),descriptionEn:val(formData,"descriptionEn"),locationDescriptionEn:val(formData,"locationDescriptionEn"),seoTitleEn:val(formData,"seoTitleEn"),seoDescriptionEn:val(formData,"seoDescriptionEn")});const pool=getPool();const values=[data.category,data.status,data.title,data.subtitle,data.slug,data.shortDescription,data.description,data.address,data.city,data.locationDescription,data.heroImage,data.mapAddress,data.featured,data.showInNavigation,data.seoTitle||null,data.seoDescription||null,data.titleEn||null,data.subtitleEn||null,data.shortDescriptionEn||null,data.descriptionEn||null,data.locationDescriptionEn||null,data.seoTitleEn||null,data.seoDescriptionEn||null];if(id){await pool.execute("UPDATE projects SET category=?,status=?,title=?,subtitle=?,slug=?,shortDescription=?,description=?,address=?,city=?,locationDescription=?,heroImage=?,mapAddress=?,featured=?,showInNavigation=?,seoTitle=?,seoDescription=?,titleEn=?,subtitleEn=?,shortDescriptionEn=?,descriptionEn=?,locationDescriptionEn=?,seoTitleEn=?,seoDescriptionEn=? WHERE id=?",[...values,id]);}else{await pool.execute("INSERT INTO projects (category,status,title,subtitle,slug,shortDescription,description,address,city,locationDescription,heroImage,mapAddress,featured,showInNavigation,seoTitle,seoDescription,titleEn,subtitleEn,shortDescriptionEn,descriptionEn,locationDescriptionEn,seoTitleEn,seoDescriptionEn) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",values);}refreshProjects();redirect("/admin/projects");}
function fdNumber(fd:FormData,key:string){return Number(fd.get(key)||0)}
export async function deleteProjectAction(formData:FormData){await guard();const id=z.number().int().positive().parse(fdNumber(formData,"id"));await getPool().execute("DELETE FROM projects WHERE id=?",[id]);refreshProjects();redirect("/admin/projects");}
export async function saveTeamMemberAction(formData:FormData){await guard();const id=fdNumber(formData,"id"),values=[val(formData,"name"),val(formData,"role"),val(formData,"photo"),val(formData,"description"),formData.get("active")==="on"];if(id)await getPool().execute("UPDATE team_members SET name=?,role=?,photo=?,description=?,active=? WHERE id=?",[...values,id]);else await getPool().execute("INSERT INTO team_members(name,role,photo,description,active) VALUES(?,?,?,?,?)",values);revalidatePath("/o-nama");redirect("/admin/team");}
export async function saveSettingsAction(formData:FormData){await guard();const keys=["companyName","phone","email","address","instagram","linkedin","facebook","contactHeading","contactText","aboutTitle","aboutSubtitle","aboutDescription","aboutImage","footerText"];const pool=getPool();for(const key of keys)await pool.execute("INSERT INTO site_settings(settingKey,settingValue) VALUES(?,?) ON DUPLICATE KEY UPDATE settingValue=VALUES(settingValue)",[key,val(formData,key)]);revalidatePath("/","layout");redirect("/admin/settings");}
export async function addUnitAction(formData:FormData){await guard();const projectId=fdNumber(formData,"projectId");await getPool().execute("INSERT INTO units(projectId,name,unitNumber,floor,rooms,area,orientation,price,showPrice,status) VALUES(?,?,?,?,?,?,?,?,?,?)",[projectId,val(formData,"name"),val(formData,"unitNumber"),val(formData,"floor"),val(formData,"rooms")||null,fdNumber(formData,"area"),val(formData,"orientation"),val(formData,"price")||null,formData.get("showPrice")==="on",val(formData,"status")]);refreshProjects();revalidatePath(`/admin/projects/${projectId}`);redirect(`/admin/projects/${projectId}`);}
export async function deleteUnitAction(formData:FormData){await guard();const projectId=fdNumber(formData,"projectId");await getPool().execute("DELETE FROM units WHERE id=? AND projectId=?",[fdNumber(formData,"id"),projectId]);refreshProjects();revalidatePath(`/admin/projects/${projectId}`);}
export async function addImageAction(formData:FormData){await guard();const projectId=fdNumber(formData,"projectId");await getPool().execute("INSERT INTO project_images(projectId,imagePath,altText,type) VALUES(?,?,?,?)",[projectId,val(formData,"imagePath"),val(formData,"altText"),val(formData,"type")]);refreshProjects();revalidatePath(`/admin/projects/${projectId}`);redirect(`/admin/projects/${projectId}`);}
export async function deleteImageAction(formData:FormData){await guard();const projectId=fdNumber(formData,"projectId");await getPool().execute("DELETE FROM project_images WHERE id=? AND projectId=?",[fdNumber(formData,"id"),projectId]);refreshProjects();revalidatePath(`/admin/projects/${projectId}`);}
export async function addFloorPlanAction(formData:FormData){await guard();const projectId=fdNumber(formData,"projectId");await getPool().execute("INSERT INTO project_floor_plans(projectId,title,image,description) VALUES(?,?,?,?)",[projectId,val(formData,"title"),val(formData,"image"),val(formData,"description")]);refreshProjects();revalidatePath(`/admin/projects/${projectId}`);redirect(`/admin/projects/${projectId}`);}
export async function updateInquiryStatusAction(formData:FormData){await guard();const status=z.enum(["NEW","READ","ARCHIVED"]).parse(val(formData,"status"));await getPool().execute("UPDATE inquiries SET status=? WHERE id=?",[status,fdNumber(formData,"id")]);revalidateTag("inquiries","max");revalidatePath("/admin/inquiries");}
export async function logoutAction(){await destroySession();redirect("/admin/login");}
